name: Tox Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential       # GNU C++ compiler
          sudo apt install libboost-all-dev      # C++ libraries provided by Boost
          sudo apt install swig                  # Python to C++ bridge

      - name: Run Tox tests
        uses: Somerandomguy10111/actions/toxtests@main
        with:
          python-version: '3.11'
